service_name := 'backend'

default:
  @just --list

# Build image
build:
  @docker-compose build '{{service_name}}'

# Push image
push:
  @docker-compose --env-file .env-prod '{{service_name}}'

# Start service
up:
  @docker-compose up --detach '{{service_name}}'

# Stop container
down:
  @docker-compose down '{{service_name}}'

# Run shell inside container
shell:
  @docker-compose run --volume "$PWD":/app:rw --workdir /app --entrypoint /bin/sh --rm '{{service_name}}'

# Run command inside container
run command:
  @docker-compose run --volume "$PWD":/app:rw --workdir /app --entrypoint /bin/sh --rm '{{service_name}}' -c '{{command}}'

watch:
  @docker-compose watch --no-up '{{service_name}}'
